#pragma once

#define MATRIX_ROWS 2
#define MATRIX_COLS 4

#define MATRIX_ROW_PINS { GP2, GP3 }
#define MATRIX_COL_PINS { GP4, GP5, GP6, GP7 }

#define DIODE_DIRECTION COL2ROW

// Encoder
#define ENCODERS_PAD_A { GP8 }
#define ENCODERS_PAD_B { GP9 }
#define ENCODER_RESOLUTION 4

// OLED (I2C)
#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP0
#define I2C1_SCL_PIN GP1
#define OLED_TIMEOUT 30000

// SK6812 RGB
#define RGB_DI_PIN GP10
#define RGBLED_NUM 9
#define RGBLIGHT_LIMIT_VAL 150

#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_STATIC_LIGHT

#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_BREATHING
#define RGBLIGHT_DEFAULT_HUE 180
#define RGBLIGHT_DEFAULT_SAT 255
#define RGBLIGHT_DEFAULT_VAL 120